name: Server Configuration via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "echo 'SSH connection successful!'"

    - name: Configure Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script_timeout: 10m
        script: |
          set -e
          echo "Starting server configuration..."
          
          # Обновление системы
          apt-get update -qq
          apt-get upgrade -y -qq
          apt-get install -y -qq mc htop fail2ban
          
          # Настройка SSH
          echo "Configuring SSH..."
          sed -i 's/#Port 22/Port 49009/g' /etc/ssh/sshd_config
          sed -i 's/Port 22/Port 49009/g' /etc/ssh/sshd_config
          systemctl restart sshd
          
          # Настройка BBR
          echo "Configuring BBR..."
          echo "net.core.default_qdisc=fq" | tee -a /etc/sysctl.conf
          echo "net.ipv4.tcp_congestion_control=bbr" | tee -a /etc/sysctl.conf
          sysctl -p
          
          # Настройка fail2ban
          echo "Configuring fail2ban..."
          cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
          sed -i 's/backend = auto/backend = systemd/g' /etc/fail2ban/jail.local
          systemctl restart fail2ban
          
          echo "Server configuration completed successfully!"

    - name: Verify Configuration
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 49009
        script: |
          echo "BBR Status:"
          sysctl net.ipv4.tcp_available_congestion_control
          sysctl net.ipv4.tcp_congestion_control
          
          echo "SSH Port:"
          ss -tulnp | grep ssh
          
          echo "fail2ban Status:"
          systemctl status fail2ban --no-pager
